project:
  type: book

book:
  title: "Essential Techniques"
  author: "Guanglai Li"
  date: "10/15/2023"
  chapters:
    - index.qmd
    - quarto_essentials.qmd
    - docker_reproducible_env.qmd
    - regular_expression.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



